AWSTemplateFormatVersion: "2010-09-09"
Description: "Regional ACM certificate for the application load balancer"

Parameters:
  EnvironmentName:
    Type: String
    Default: dev
  ApiDomainName:
    Type: String
    Default: api.alixblu.site

Resources:
  ALBCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref ApiDomainName
      DomainValidationOptions:
        - DomainName: !Ref ApiDomainName
          ValidationDomain: !Ref ApiDomainName
      ValidationMethod: DNS
      Tags:
        - Key: Name
          Value: !Sub book-manager-${EnvironmentName}-alb-cert

Outputs:
  ALBCertificateArn:
    Description: ACM certificate ARN for ALB
    Value: !Ref ALBCertificate
    Export:
      Name: !Sub book-manager-${EnvironmentName}-alb-certificate-arn

